"""Atualizando index id_cliente

Revision ID: 10c48839514c
Revises: 
Create Date: 2024-05-27 00:36:09.649647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '10c48839514c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('CEP', sa.Integer(), nullable=False),
    sa.Column('usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha_eletronica', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('CPF_CNPJ', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('CPF_CNPJ')
    )
    op.create_index(op.f('ix_cliente_id_cliente'), 'cliente', ['id_cliente'], unique=True)
    op.create_table('conta',
    sa.Column('n_conta', sa.Integer(), nullable=False),
    sa.Column('clientes_CPF_CNPJ', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['clientes_CPF_CNPJ'], ['cliente.CPF_CNPJ'], ),
    sa.PrimaryKeyConstraint('n_conta')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conta')
    op.drop_index(op.f('ix_cliente_id_cliente'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
