"""Criando Tabelas

Revision ID: 6fd414da1962
Revises: 
Create Date: 2024-05-26 22:36:16.782864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6fd414da1962'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banco',
    sa.Column('n_banco', sa.Integer(), nullable=False),
    sa.Column('nome_banco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('n_banco')
    )
    op.create_table('chave_pix',
    sa.Column('chave_pix', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('chave_pix')
    )
    op.create_table('cliente',
    sa.Column('CPF_CNPJ', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('CEP', sa.Integer(), nullable=False),
    sa.Column('usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha_eletronica', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('CPF_CNPJ')
    )
    op.create_table('movimento',
    sa.Column('id_movimento', sa.Integer(), nullable=False),
    sa.Column('nome_movimento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_movimento')
    )
    op.create_table('status_transacao',
    sa.Column('id_status_transacao', sa.Integer(), nullable=False),
    sa.Column('nome_status_transacao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_status_transacao')
    )
    op.create_table('agencia',
    sa.Column('n_agencia', sa.Integer(), nullable=False),
    sa.Column('banco_n_banco', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banco_n_banco'], ['banco.n_banco'], ),
    sa.PrimaryKeyConstraint('n_agencia')
    )
    op.create_table('conta',
    sa.Column('n_conta', sa.Integer(), nullable=False),
    sa.Column('clientes_CPF_CNPJ', sa.Integer(), nullable=False),
    sa.Column('chave_pix_chave_pix', sa.Integer(), nullable=True),
    sa.Column('saldo', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['chave_pix_chave_pix'], ['chave_pix.chave_pix'], ),
    sa.ForeignKeyConstraint(['clientes_CPF_CNPJ'], ['cliente.CPF_CNPJ'], ),
    sa.PrimaryKeyConstraint('n_conta')
    )
    op.create_table('agencia_has_conta',
    sa.Column('agencia_n_agencia', sa.Integer(), nullable=False),
    sa.Column('conta_n_conta', sa.Integer(), nullable=False),
    sa.Column('conta_clientes_CPFCNPJ', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agencia_n_agencia'], ['agencia.n_agencia'], ),
    sa.ForeignKeyConstraint(['conta_clientes_CPFCNPJ'], ['cliente.CPF_CNPJ'], ),
    sa.ForeignKeyConstraint(['conta_n_conta'], ['conta.n_conta'], ),
    sa.PrimaryKeyConstraint('agencia_n_agencia', 'conta_n_conta')
    )
    op.create_table('banco_has_agencia',
    sa.Column('banco_n_banco', sa.Integer(), nullable=False),
    sa.Column('agencia_n_agencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agencia_n_agencia'], ['agencia.n_agencia'], ),
    sa.ForeignKeyConstraint(['banco_n_banco'], ['banco.n_banco'], ),
    sa.PrimaryKeyConstraint('banco_n_banco', 'agencia_n_agencia')
    )
    op.create_table('transacao',
    sa.Column('id_transacao', sa.Integer(), nullable=False),
    sa.Column('n_conta_origem', sa.Integer(), nullable=False),
    sa.Column('n_conta_destino', sa.Integer(), nullable=False),
    sa.Column('movimento_id_movimento', sa.Integer(), nullable=False),
    sa.Column('data_liquidacao', sa.DateTime(), nullable=True),
    sa.Column('data_transacao', sa.DateTime(), nullable=False),
    sa.Column('id_status_transacao', sa.Integer(), nullable=False),
    sa.Column('valor_transacao', sa.Numeric(), nullable=False),
    sa.Column('CPFCNPJ_credor', sa.Integer(), nullable=False),
    sa.Column('CPFCNPJ_pagador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_status_transacao'], ['status_transacao.id_status_transacao'], ),
    sa.ForeignKeyConstraint(['movimento_id_movimento'], ['movimento.id_movimento'], ),
    sa.ForeignKeyConstraint(['n_conta_destino'], ['conta.n_conta'], ),
    sa.ForeignKeyConstraint(['n_conta_origem'], ['conta.n_conta'], ),
    sa.PrimaryKeyConstraint('id_transacao')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacao')
    op.drop_table('banco_has_agencia')
    op.drop_table('agencia_has_conta')
    op.drop_table('conta')
    op.drop_table('agencia')
    op.drop_table('status_transacao')
    op.drop_table('movimento')
    op.drop_table('cliente')
    op.drop_table('chave_pix')
    op.drop_table('banco')
    # ### end Alembic commands ###
